### ISSUE TITLE
React-Redux: Kanban Group Project

### ISSUE THREAD

**Issue by RiyaBulia12** [RiyaBulia12/Space-Hub#25]
### Task Link:
https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md

### Kanban Board:
https://github.com/users/RiyaBulia12/projects/6

### Collaborators:
1. @RiyaBulia12 
2. @betses

**Comment by descholar-ceo** [comment]
Hi @RiyaBulia12 && @betses 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all of the requirements ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by RiyaBulia12** [comment]
Thanks, @descholar-ceo for approving and reviewing the issue quickly.
